// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.startupExperimentPrefs.dom.push.alwaysConnect", true);
user_pref("app.normandy.user_id", "84f60953-c878-4bb4-a173-16622bc7283e");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1543722495);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1543722615);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1543757148);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1543757388);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1543757268);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1543722375);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1543722855);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1543722735);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 788480);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.download.panel.shown", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1543721985);
user_pref("browser.laterrun.bookkeeping.sessionCount", 3);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 74);
user_pref("browser.newtabpage.activity-stream.impressionId", "{09274694-192c-423e-a197-5accc62d2cbb}");
user_pref("browser.newtabpage.activity-stream.migrationLastShownDate", 1543737600);
user_pref("browser.newtabpage.activity-stream.migrationRemainingDays", 2);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.onboarding.seen-tourset-version", 2);
user_pref("browser.onboarding.tour-type", "new");
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.rights.3.shown", true);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1543757130125");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1543758948125");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1543757131227");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1543760731227");
user_pref("browser.search.region", "CN");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20181116125654");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1543757750");
user_pref("browser.slowStartup.averageTime", 7646);
user_pref("browser.slowStartup.samples", 3);
user_pref("browser.startup.homepage_override.buildID", "20181116125654");
user_pref("browser.startup.homepage_override.mstone", "63.0.3");
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"PersonalToolbar\":[\"personal-bookmarks\"],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"PersonalToolbar\",\"nav-bar\",\"toolbar-menubar\",\"TabsToolbar\"],\"currentVersion\":14,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "百度");
user_pref("browser.urlbar.timesBeforeHidingSuggestionsHint", 0);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1543722001765");
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "63.0.3");
user_pref("distribution.iniFile.exists.value", true);
user_pref("dom.push.userAgentID", "7c570e768bc64264b49d68a09735d3b5");
user_pref("extensions.blocklist.lastModified", "Mon, 26 Nov 2018 14:19:56 GMT");
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", -1);
user_pref("extensions.databaseSchema", 27);
user_pref("extensions.getAddons.cache.lastUpdate", 1543722497);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppBuildId", "20181116125654");
user_pref("extensions.lastAppVersion", "63.0.3");
user_pref("extensions.lastPlatformVersion", "63.0.3");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"b4e1db14-85f5-457b-8656-c604fbb1f51b\",\"webcompat@mozilla.org\":\"35a18e10-7e2d-45e7-b8e1-7e6159f0222f\",\"screenshots@mozilla.org\":\"e663b1df-c99c-44e9-802b-06cd8316fb87\",\"fxmonitor@mozilla.org\":\"4c5599da-b380-42ba-8bb0-57cc829b8ebd\"}");
user_pref("lightweightThemes.usedThemes", "[]");
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1543722517);
user_pref("media.gmp-gmpopenh264.version", "1.7.1");
user_pref("media.gmp-manager.buildID", "20181116125654");
user_pref("media.gmp-manager.lastCheck", 1543757405);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.pending", "[{\"id\":\"newtab-container\",\"itemsToClear\":[],\"options\":{}}]");
user_pref("security.sandbox.content.tempDirSuffix", "4629b31f-c868-4a68-9dc8-1af06db3ce14");
user_pref("services.blocklist.addons.checked", 1543607080);
user_pref("services.blocklist.gfx.checked", 1543607080);
user_pref("services.blocklist.onecrl.checked", 1543607080);
user_pref("services.blocklist.pinning.checked", 1543607080);
user_pref("services.blocklist.plugins.checked", 1543607080);
user_pref("services.settings.clock_skew_seconds", 150325);
user_pref("services.settings.last_update_seconds", 1543607080);
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1543757747);
user_pref("toolkit.telemetry.cachedClientID", "7108f2b7-0363-475c-9310-525c7f3d4618");
user_pref("toolkit.telemetry.previousBuildID", "20181116125654");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
